# ----- Step 0: Workspace setup ----- #

library("testthat")
library("dplyr")
library("duckdb")
library("rprojroot")
library("glue")

# Make sure the working directory is correct
root <- find_root(is_rstudio_project)
setwd(root)

# Load your package (assuming write_race_eth_sql_query is part of dataduck)
devtools::load_all("../dataduck")

# ----- Step 1: Create test inputs ----- #

# Define a tibble representing the data to be manipulated
input_tb <- tibble::tibble(
  pers_id = 1:6,
  HISPAN_bucket = c("not_hispanic", "hispanic", "hispanic", "not_hispanic", "not_hispanic", "hispanic"),
  RACE_bucket = c("white", "white", "black", "aapi", "black", "multi")
)

# Expected output after applying the SQL query
expected_tb <- tibble::tibble(
  pers_id = 1:6,
  HISPAN_bucket = c("not_hispanic", "hispanic", "hispanic", "not_hispanic", "not_hispanic", "hispanic"),
  RACE_bucket = c("white", "white", "black", "aapi", "black", "multi"),
  RACE_ETH_bucket = c("White", "Hispanic", "Hispanic", "AAPI", "Black", "Hispanic")
)

# ----- Step 2: Create DuckDB connection and run test ----- #

test_that("write_race_eth_sql_query correctly manipulates DuckDB table", {
  
  # Set up DuckDB connection and load input tibble in
  test_con <- dbConnect(duckdb::duckdb(), ":memory:")
  dbWriteTable(test_con, "ipums", input_tb)
  
  # Apply the SQL query generated by write_race_eth_sql_query
  sql_query <- write_race_eth_sql_query("ipums")
  dbExecute(test_con, sql_query)
  
  result_tb <- tbl(test_con, "ipums") |>
    collect() |>
    arrange(pers_id)
  
  # Test that the actual result matches the expected result
  expect_equal(result_tb, expected_tb)
  
  # Clean up: disconnect from DuckDB
  dbDisconnect(test_con, shutdown = TRUE)
  
})

